version: 0.2

phases:
  install:
    commands:
      - echo Entering install phase...
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn -f pom.xml compile war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  type: zip
  files:
    - 'ROOT/WEB-INF/classes/application.properties'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/HelloWorldAppInitializer.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/*'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/controller/*'
   - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/model/*'
   - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/dao/*'
    
    - 'ROOT/WEB-INF/lib/*'
    - 'ROOT/WEB-INF/views/*'
    - 'ROOT/resources/gradients.css'
    - 'ROOT/resources/set-background.js'
    - 'ROOT/resources/styles.css'
    - 'ROOT/resources/tweet.svg'
